"""add skill_tools registry table

Revision ID: 9d77390fe3f6
Revises: 11802f9f44aa
Create Date: 2026-08-13 11:37:49.379744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d77390fe3f6'
down_revision: Union[str, Sequence[str], None] = '11802f9f44aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_tools',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('tool', 'skill', name='skill_tool_kind'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('builtin', 'shared', 'private', name='skill_tool_source'), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('impl_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_tools')
    # ### end Alembic commands ###
